name: Test Brick Layer still works

on:
    pull_request:
        paths:
            - bricklayers.py
    workflow_dispatch:

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                py: [3.13, pypy3.11]
        name: Bricklayer on ${{ matrix.os }} with ${{ matrix.py }}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with: 
                python-version: ${{ matrix.py }}
                check-latest: true
            - name: Run bricklayer.py
              run: |
                python3 ./bricklayers.py \
                ./sample_gcode/Sample_BrickLayersChallengeSimple_5walls.gcode \
                -outputFile ./sample_brick/SampleBrickLayersChallengeSimple_5walls_brick.gcode \
                -extrusionMultiplier 1.05 \
                -verbosity 1
            - name: Upload generated gcode
              uses: actions/upload-artifact@v4
              with:
                name: brick-${{ matrix.os }}-${{ matrix.py }}-${{github.ref}}
                path: ./sample_brick/SampleBrickLayersChallengeSimple_5walls_brick.gcode
                if-no-files-found: error
                retention-days: 90


